### ISSUE TITLE
Criação do documento de contexto e levantamento dos dados.

### ISSUE THREAD

**Issue by gstvcastroc** [ICEI-PUC-Minas-PMV-SI/pmv-si-2024-1-pe7-t1-twittersentimentanalysis#1]
Será abringido a criação do documento de contexto e o levantamento dos dados necessários para o andamento do projeto, com todos os seus pontos a serem discutidos, sendo eles:

- [x] Introdução; #2 
- [x] Problema; #3 
- [x] Questão de pesquisa; #4 
- [x] Justificativa; #5 
- [x] Público-alvo; #6 
- [ ] Estado da arte; #7 
- [x] Descrição do dataset selecionado; #8 
- [x] Canvas analítico; #9
